#version 450 core
layout(local_size_x = 8, local_size_y = 8) in;
layout(std430, binding = 0) buffer Grid
{
    float values[512][512];  // height x width
};

void main() {
	ivec2 ppos = ivec2(mod(gl_GlobalInvocationID.xy, 512));

	values[ppos.y][ppos.x] = float(min(mod(floor(ppos.x), 511.0), mod(floor(ppos.y), 511.0)) == 0.0);

	if(ppos.x == 14 && ppos.y > 2)
	{
		values[ppos.y][ppos.x] = 1.0;
	}
}